# github repository Actions 페이지에 나타낼 이름
name: Java CD with Gradle

# event trigger
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

permissions:
  contents: read

jobs:
  build:
    ## ubuntu version
    runs-on: ubuntu-18.04

    steps:

      ## gradle cashing -> 나중에 빌드시간을 줄이고 싶을때 적용해보자

      ## checkout
      - uses: actions/checkout@v3
      ## jdk setting
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'


      ## application properties 환경별로 설정 하기
      # main브랜치인 경우 application.properties파일 제작한다.
      - name: Main Branch Make application-prd.properties
        if: contains(github.ref, 'main')
        run: |
          cd ./src/main/resources
          touch ./application-prd.properties
          echo "${{ secrets.PROPERTIES_PRD }}" > ./application-prd.properties
        shell: bash

      ## Gradle 권한 부여
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        shell: bash

      # 테스트 진행
      - name: main Test
        if: contains(github.ref, 'main')
        run: ./gradlew clean test
        shell: bash

      # 프로젝트 테스트 진행없이 빌드
      - name: Build with Gradle
        run: ./gradlew build -x test
        shell: bash

      # 운영서버에 배포

      # 전송할 파일을 담을 디렉토리 생성
      - name: Make Directory for deliver
        run: mkdir deploy

      # Jar 파일 Copy
      - name: Copy Jar
        run: cp ./build/libs/*.jar ./deploy/

      # 압축파일 형태로 전달
      - name: Make zip file
        run: zip -r -qq -j ./springboot-intro-build.zip ./deploy

      # S3 Bucket으로 copy
      - name: Deliver to AWS S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp \
          --region ap-northeast-2 \
          --acl private \
          ./springboot-intro-build.zip s3://springboot-intro-build/